---
# tasks file for ansible-role-sshd-host-keys
#

- name: fetch the host keys from the shared FS and install into /etc/ssh/
  fetch: >
    src="{{ ssh_host_keys_dir }}/{{ ansible_hostname }}/ssh/{{ item[0] }}{{ item[1] }}"
    dest="/etc/ssh/"
    owner=root group=ssh_keys mode=0640 backup=no 
    validate_checksum=yes fail_on_missing=yes
    flat=yes
  with_nested: 
   - ssh_host_key_files
   - [ "", ".pub" ]
