---
# tasks file for ansible-role-sshd-host-keys
#

- name: get_url the known_hosts files to /etc/ssh/
  get_url: url={{ known_hosts_url }}/{{ item }} dest=/etc/ssh/{{ item }} owner=root group=root mode=0644 backup=no force=yes
  with_items: ssh_known_host_files

- name: lineinfile - GlobalKnownHostsFile in /etc/ssh/ssh_config for each known_hosts file
  lineinfile: dest=/etc/ssh/ssh_config regexp='^GlobalKnownHostsFile /etc/ssh/{{ item }}$' line="GlobalKnownHostsFile /etc/ssh/{{ item }}" state=present
  with_items: ssh_known_host_files
